-- 1
SELECT 
    SS.STAND_NAME AS START_STAND,
    ES.STAND_NAME AS END_STAND,
    GET_INTERMEDIATE_STANDS(R.ROUTE_ID) AS INTERMEDIATE_STANDS,
    GET_TOTAL_DISTANCE(R.ROUTE_ID) AS DISTANCE 
    FROM ROUTE R 
    JOIN STAND SS 
    ON R.START_STAND_ID=SS.STAND_ID 
    JOIN STAND ES 
    ON R.END_STAND_ID=ES.STAND_ID 
    JOIN DISTANCE D 
    ON R.START_STAND_ID=D.STARTING_STAND AND R.END_STAND_ID=D.ENDING_STAND

-- 2
INSERT INTO ROUTE (ROUTE_ID, START_STAND_ID, END_STAND_ID) 
VALUES (${routeId.rows[0].NEXTVAL}, GET_STAND_ID(:startStandName), GET_STAND_ID(:endStandName))

-- 3
SELECT DISTINCT START_S.STAND_NAME AS START_STAND,
    END_S.STAND_NAME AS END_STAND, 
    D.TRAVEL_DISTANCE AS DISTANCE, 
    BC.BUS_COMPANY_NAME AS BUS_COMPANY_NAME, 
    B.BUS_TYPE, 
    D.TRAVEL_DISTANCE*B.TICKET_PRICE AS TOTAL_COST, 
    B.BUS_RATING AS BUS_RATING
    FROM BUS B 
    JOIN ROUTE R ON B.ROUTE_ID = R.ROUTE_ID
    JOIN DISTANCE D ON R.START_STAND_ID = D.STARTING_STAND AND R.END_STAND_ID= D.ENDING_STAND
    JOIN STAND START_S ON D.STARTING_STAND = START_S.STAND_ID
    JOIN STAND END_S ON D.ENDING_STAND = END_S.STAND_ID
    JOIN BUS_COMPANY BC ON B.BUS_COMPANY_ID = BC.BUS_COMPANY_ID

-- 4
SELECT DISTINCT GET_BUS_COMPANY_NAME(BUS_ID) AS BUS_COMPANY_NAME,
    (SELECT BUS_TYPE FROM BUS WHERE BUS.BUS_ID = TICKET.BUS_ID) AS BUS_TYPE,
    GET_STAND_NAME(STARTING_STAND) AS START_STAND, 
    GET_STAND_NAME(ENDING_STAND) AS END_STAND,
    TO_CHAR(TRAVEL_TIME, 'DD MON, YYYY') AS TRAVEL_DATE,
    TO_CHAR(TRAVEL_TIME, 'HH24:MI:SS') AS TRAVEL_TIME,
    GET_SEAT_NUMBERS(USER_ID, BUS_ID, STARTING_STAND, ENDING_STAND, TRAVEL_TIME) AS SEAT_NUMBER,
    GET_TOTAL_PRICE(USER_ID, BUS_ID, STARTING_STAND, ENDING_STAND, TRAVEL_TIME) AS TICKET_PRICE
    FROM TICKET 
    WHERE USER_ID = ${req.session.user} 
    AND TRAVEL_TIME > SYSDATE
    ORDER BY TRAVEL_DATE ASC,TRAVEL_TIME ASC   

-- 5
DECLARE
    B_ID NUMBER;
    BEGIN
    SELECT BUS_ID 
    INTO B_ID
    FROM BUS 
    WHERE BUS_COMPANY_ID=
        (SELECT BUS_COMPANY_ID 
        FROM BUS_COMPANY
        WHERE BUS_COMPANY_NAME='${result2[i].BUS_COMPANY_NAME}')
    AND BUS_TYPE='${result2[i].BUS_TYPE}'
    AND SCHEDULE_ID IN
        (SELECT SCHEDULE_ID
        FROM SCHEDULE_TIME
        WHERE T_TIME=
        INTERVAL '${result2[i].TRAVEL_TIME}' HOUR TO SECOND)
    AND ROUTE_ID=
        (SELECT R1.ROUTE_ID 
        FROM (SELECT ROUTE_ID 
        FROM ROUTE_STAND 
        WHERE STAND_ID=
            (SELECT STAND_ID 
            FROM STAND Y
            WHERE STAND_NAME='${result2[i].START_STAND}')) R1
        JOIN (SELECT ROUTE_ID 
            FROM ROUTE_STAND 
            WHERE STAND_ID=
            (SELECT STAND_ID 
            FROM STAND 
            WHERE STAND_NAME='${result2[i].END_STAND}')) R2 
        ON R1.ROUTE_ID=R2.ROUTE_ID);
    INSERT INTO LOG VALUES(SEQ_LOG.NEXTVAL,'GET_BUS_COMPANY_NAME',SYSDATE,B_ID);
    INSERT INTO LOG VALUES(SEQ_LOG.NEXTVAL,'GET_STAND_NAME',SYSDATE,'${result2[i].START_STAND}');
    INSERT INTO LOG VALUES(SEQ_LOG.NEXTVAL,'GET_STAND_NAME',SYSDATE,'${result2[i].END_STAND}');
    INSERT INTO LOG VALUES(SEQ_LOG.NEXTVAL,'GET_SEAT_NUMBERS',SYSDATE,'${req.session.user}'||', '||B_ID||', '||'${result2[i].START_STAND}'||', '||'${result2[i].END_STAND}'||', '||'${result2[i].TRAVEL_TIME}');
    INSERT INTO LOG VALUES(SEQ_LOG.NEXTVAL,'GET_TOTAL_PRICE',SYSDATE,'${req.session.user}'||', '||B_ID||', '||'${result2[i].START_STAND}'||', '||'${result2[i].END_STAND}'||', '||'${result2[i].TRAVEL_TIME}');
    COMMIT;
    END;

-- 6
SELECT BUS_ID 
FROM BUS 
WHERE BUS_COMPANY_ID=
    (SELECT BUS_COMPANY_ID 
    FROM BUS_COMPANY
    WHERE BUS_COMPANY_NAME='${result3[i].BUS_COMPANY_NAME}')
AND BUS_TYPE='${result3[i].BUS_TYPE}'
AND SCHEDULE_ID=
    (SELECT SCHEDULE_ID
    FROM SCHEDULE_TIME
    WHERE T_TIME=
    INTERVAL '${result3[i].TRAVEL_TIME}' HOUR TO SECOND)
AND ROUTE_ID=
    (SELECT R1.ROUTE_ID 
    FROM (SELECT ROUTE_ID 
    FROM ROUTE_STAND 
    WHERE STAND_ID=
        (SELECT STAND_ID 
        FROM STAND Y
        WHERE STAND_NAME='${result3[i].START_STAND}')) R1
    JOIN (SELECT ROUTE_ID 
        FROM ROUTE_STAND 
        WHERE STAND_ID=
        (SELECT STAND_ID 
        FROM STAND 
        WHERE STAND_NAME='${result3[i].END_STAND}')) R2 
    ON R1.ROUTE_ID=R2.ROUTE_ID)

-- 7
SELECT R1.ROUTE_ID
    FROM ROUTE_STAND R1
    JOIN ROUTE_STAND R2 
    ON R1.STAND_ID=(
      SELECT STAND_ID
      FROM STAND 
      WHERE STAND_NAME='${startingStand}')
    AND R2.STAND_ID=(
      SELECT STAND_ID
      FROM STAND 
      WHERE STAND_NAME='${endingStand}')
    AND R1.ROUTE_ID=R2.ROUTE_ID

-- 8
SELECT BUS_ID 
      FROM BUS 
      WHERE BUS_COMPANY_ID=
        (SELECT BUS_COMPANY_ID 
        FROM BUS_COMPANY
        WHERE BUS_COMPANY_NAME='${busCompanyName}')
      AND BUS_TYPE='${busType}'
      AND SCHEDULE_ID=
        (SELECT SCHEDULE_ID
        FROM SCHEDULE_TIME
        WHERE T_TIME=
        INTERVAL '${travelTime}' HOUR TO SECOND)
      AND ROUTE_ID=
        (SELECT R1.ROUTE_ID 
        FROM (SELECT ROUTE_ID 
          FROM ROUTE_STAND 
          WHERE STAND_ID=
            (SELECT STAND_ID 
            FROM STAND Y
            WHERE STAND_NAME='${startingStand}')) R1
          JOIN (SELECT ROUTE_ID 
            FROM ROUTE_STAND 
            WHERE STAND_ID=
              (SELECT STAND_ID 
              FROM STAND 
              WHERE STAND_NAME='${endingStand}')) R2 
          ON R1.ROUTE_ID=R2.ROUTE_ID)

-- 9
SELECT * 
    FROM REVIEW 
    WHERE USER_ID = ${req.session.user}
    AND BUS_ID = (
        SELECT BUS_ID 
        FROM BUS 
        WHERE BUS_COMPANY_ID = (
            SELECT BUS_COMPANY_ID 
            FROM BUS_COMPANY
            WHERE BUS_COMPANY_NAME = '${busCompanyName}'
        )
        AND BUS_TYPE = '${busType}'
        AND SCHEDULE_ID = (
            SELECT SCHEDULE_ID
            FROM SCHEDULE_TIME
            WHERE T_TIME = INTERVAL '${travelTime}' HOUR TO SECOND
        )
        AND ROUTE_ID = (
            SELECT R1.ROUTE_ID 
            FROM (
                SELECT ROUTE_ID 
                FROM ROUTE_STAND 
                WHERE STAND_ID = (
                    SELECT STAND_ID 
                    FROM STAND Y
                    WHERE STAND_NAME = '${startingStand}'
                )
            ) R1
            JOIN (
                SELECT ROUTE_ID 
                FROM ROUTE_STAND 
                WHERE STAND_ID = (
                    SELECT STAND_ID 
                    FROM STAND 
                    WHERE STAND_NAME = '${endingStand}'
                )
            ) R2 ON R1.ROUTE_ID = R2.ROUTE_ID
        )
    )

-- 10
INSERT INTO REVIEW 
VALUES(${req.session.user}, 
    (SELECT BUS_ID FROM BUS WHERE BUS_COMPANY_ID = 
    (SELECT BUS_COMPANY_ID FROM BUS_COMPANY 
        WHERE BUS_COMPANY_NAME = :busCompanyName )
    AND BUS_TYPE = :busType 
    AND ROUTE_ID = 
        (SELECT ROUTE_ID FROM ROUTE WHERE 
            (
            START_STAND_ID <= GET_STAND_ID(:startingStand) 
            AND END_STAND_ID >= GET_STAND_ID(:endingStand) 
            ) 
        )
    ), ${stars}, :review)

-- 11
SELECT 
        (SELECT TRAVEL_DISTANCE
        FROM DISTANCE
        WHERE STARTING_STAND=
          (SELECT STAND_ID
          FROM STAND
          WHERE STAND_NAME='${startStandName}')
        AND ENDING_STAND=
          (SELECT STAND_ID
          FROM STAND
          WHERE STAND_NAME='${endStandName}')
        ) AS DISTANCE,
        TICKET_PRICE,
        BUS_RATING,
        BUS_TYPE,
        (SELECT BUS_RELATED_MEDIA
        FROM BUS_COMPANY BC
        WHERE BC.BUS_COMPANY_ID=B.BUS_COMPANY_ID) AS BUS_RELATED_MEDIA,
        (SELECT BUS_COMPANY_NAME
        FROM BUS_COMPANY BC
        WHERE BC.BUS_COMPANY_ID=B.BUS_COMPANY_ID) AS BUS_COMPANY_NAME
      FROM BUS B
      WHERE B.BUS_COMPANY_ID IN
          (SELECT BUS_COMPANY_ID
          FROM BUS_COMPANY
          WHERE BUS_COMPANY_NAME LIKE '${busCompany}')
      AND BUS_TYPE LIKE '${busType}'
      AND ROUTE_ID=
        (SELECT RS1.ROUTE_ID
        FROM ROUTE_STAND RS1
        JOIN ROUTE_STAND RS2
        ON RS1.STAND_ID=
          (SELECT STAND_ID
          FROM STAND
          WHERE STAND_NAME='${startStandName}')
        AND RS2.STAND_ID=
          (SELECT STAND_ID
          FROM STAND
          WHERE STAND_NAME='${endStandName}')
        AND RS1.ROUTE_ID=RS2.ROUTE_ID)

-- 12
 SELECT D.TRAVEL_DISTANCE AS DIST 
FROM DISTANCE D 
WHERE D.STARTING_STAND=
    (SELECT STAND_ID FROM STAND 
    WHERE STAND_NAME='${startStandName}') 
    AND D.ENDING_STAND=(SELECT STAND_ID FROM STAND 
    WHERE STAND_NAME='${endStandName}')

-- 13 
SELECT R1.ROUTE_ID 
      FROM ROUTE_STAND R1
      JOIN ROUTE_STAND R2 
      ON R1.STAND_ID=(
        SELECT STAND_ID 
        FROM STAND
        WHERE STAND_NAME='${startStandName}')
      AND R2.STAND_ID=(
        SELECT STAND_ID 
        FROM STAND 
        WHERE STAND_NAME='${endStandName}')
      AND R1.ROUTE_ID=R2.ROUTE_ID

-- 14 
SELECT B.*,
      (SELECT BUS_COMPANY_NAME
      FROM BUS_COMPANY BC
      WHERE BC.BUS_COMPANY_ID=B.BUS_COMPANY_ID) AS BUS_COMPANY_NAME,
      (SELECT BUS_RELATED_MEDIA
        FROM BUS_COMPANY BC
        WHERE BC.BUS_COMPANY_ID=B.BUS_COMPANY_ID) AS BUS_RELATED_MEDIA
      FROM BUS B
      WHERE BUS_TYPE='${busType}'
      AND SCHEDULE_ID IN
        (SELECT SCHEDULE_ID
        FROM SCHEDULE_TIME
        WHERE T_TIME=
        INTERVAL '${time+":00"}' HOUR TO SECOND)
      AND ROUTE_ID=
        (SELECT RS1.ROUTE_ID
        FROM ROUTE_STAND RS1
        JOIN ROUTE_STAND RS2
        ON RS1.STAND_ID=
          (SELECT STAND_ID
          FROM STAND 
          WHERE STAND_NAME='${startStandName}')
        AND RS2.STAND_ID=
          (SELECT STAND_ID
          FROM STAND
          WHERE STAND_NAME='${endStandName}')
        AND RS1.ROUTE_ID=RS2.ROUTE_ID)

-- 15
SELECT * FROM EVENT 
    WHERE DISCOUNT=(
    SELECT MAX(DISCOUNT) FROM EVENT 
    WHERE EVENT_START_TIME<=TO_DATE('${date}','YYYY-MM-DD') 
    AND EVENT_END_TIME>=TO_DATE('${date}','YYYY-MM-DD')
    )
AND EVENT_START_TIME<=TO_DATE('${date}','YYYY-MM-DD') 
AND EVENT_END_TIME>=TO_DATE('${date}','YYYY-MM-DD')

-- 16
SELECT BUS_ID 
    FROM BUS 
    WHERE BUS_COMPANY_ID=
      (SELECT BUS_COMPANY_ID 
      FROM BUS_COMPANY
      WHERE BUS_COMPANY_NAME='${busCompany}')
    AND BUS_TYPE='${busType}'
    AND SCHEDULE_ID IN
      (SELECT SCHEDULE_ID
      FROM SCHEDULE_TIME
      WHERE T_TIME=
      INTERVAL '${time+":00"}' HOUR TO SECOND)
    AND ROUTE_ID=
      (SELECT R1.ROUTE_ID 
      FROM (SELECT ROUTE_ID 
        FROM ROUTE_STAND 
        WHERE STAND_ID=
          (SELECT STAND_ID 
          FROM STAND Y
          WHERE STAND_NAME='${startStandName}')) R1
        JOIN (SELECT ROUTE_ID 
          FROM ROUTE_STAND 
          WHERE STAND_ID=
            (SELECT STAND_ID 
            FROM STAND 
            WHERE STAND_NAME='${endStandName}')) R2 
        ON R1.ROUTE_ID=R2.ROUTE_ID)

-- 17
INSERT INTO TICKET(TICKET_ID,USER_ID,BUS_ID,TRANSACTION_ID,STARTING_STAND,ENDING_STAND,DISTANCE_ID,TRAVEL_TIME,SEAT_NUMBER,TICKET_PRICE)
VALUES(SEQ_TICKET.NEXTVAL,
${req.session.user},${busIdResult[0].BUS_ID},
${result1[0].NEXTVAL},
(SELECT STAND_ID FROM STAND WHERE STAND_NAME='${startStandName}'),
(SELECT STAND_ID FROM STAND WHERE STAND_NAME='${endStandName}'),
(SELECT D.DISTANCE_ID FROM  STAND S1 CROSS JOIN STAND S2 JOIN DISTANCE D ON (S1.STAND_ID=D.STARTING_STAND AND S2.STAND_ID=D.ENDING_STAND) WHERE S1.STAND_ID=(SELECT STAND_ID FROM STAND WHERE STAND_NAME='${startStandName}') AND S2.STAND_ID=(SELECT STAND_ID FROM STAND WHERE STAND_NAME='${endStandName}')),
TO_DATE('${travel_time}','YYYY-MM-DD HH24:MI:SS'),
'${seatNumbers[i]}',${price})

-- 18
INSERT INTO TICKET(TICKET_ID,USER_ID,BUS_ID,TRANSACTION_ID,STARTING_STAND,ENDING_STAND,DISTANCE_ID,TRAVEL_TIME,SEAT_NUMBER,TICKET_PRICE,EVENT_ID)
VALUES(SEQ_TICKET.NEXTVAL,
${req.session.user},${busIdResult[0].BUS_ID},
${result1[0].NEXTVAL},
(SELECT STAND_ID FROM STAND WHERE STAND_NAME='${startStandName}'),
(SELECT STAND_ID FROM STAND WHERE STAND_NAME='${endStandName}'),
(SELECT D.DISTANCE_ID FROM  STAND S1 CROSS JOIN STAND S2 JOIN DISTANCE D ON (S1.STAND_ID=D.STARTING_STAND AND S2.STAND_ID=D.ENDING_STAND) WHERE S1.STAND_ID=(SELECT STAND_ID FROM STAND WHERE STAND_NAME='${startStandName}') AND S2.STAND_ID=(SELECT STAND_ID FROM STAND WHERE STAND_NAME='${endStandName}')),
TO_DATE('${travel_time}','YYYY-MM-DD HH24:MI:SS'),
'${seatNumbers[i]}',${price},${event_id})

-- 19
SELECT SUM(T.TICKET_PRICE) AS REVENUE,
TO_CHAR(TRAVEL_TIME,'MONTH') AS MONTH 
FROM TICKET T 
JOIN BUS B ON T.BUS_ID=B.BUS_ID 
JOIN BUS_COMPANY BC ON BC.BUS_COMPANY_ID=B.BUS_COMPANY_ID 
WHERE BC.BUS_COMPANY_NAME='${busCompanyName}' 
GROUP BY TO_CHAR(TRAVEL_TIME,'MONTH')

-- 20
SELECT COUNT(T.TICKET_ID) AS TICKETS_SOLD,
    TO_CHAR(TRAVEL_TIME,'MONTH') AS MONTH 
    FROM TICKET T 
    JOIN BUS B ON T.BUS_ID=B.BUS_ID 
    JOIN BUS_COMPANY BC ON BC.BUS_COMPANY_ID=B.BUS_COMPANY_ID 
    WHERE BC.BUS_COMPANY_NAME='${busCompanyName}' 
    GROUP BY TO_CHAR(TRAVEL_TIME,'MONTH')

-- 21
SELECT 
(SELECT NAME FROM USER_ACCOUNT WHERE USER_ID = R.USER_ID) AS USER_NAME, 
(SELECT PROFILE_PIC FROM USER_ACCOUNT WHERE USER_ID=R.USER_ID) AS PROFILE_PIC, 
SCORE, COMMENTS,
LAST_UPDATED_ON 
FROM REVIEW R 
WHERE BUS_ID IN 
(SELECT BUS_ID FROM BUS WHERE BUS_COMPANY_ID=
    (SELECT BUS_COMPANY_ID FROM BUS_COMPANY 
    WHERE BUS_COMPANY_NAME='${busCompanyName}'))

-- 22
SELECT * FROM TICKET T 
        JOIN BUS B ON T.BUS_ID=B.BUS_ID 
        JOIN BUS_COMPANY BC ON BC.BUS_COMPANY_ID=B.BUS_COMPANY_ID 
        WHERE BC.BUS_COMPANY_NAME='${busCompanyName}'