CREATE TABLE USER_ACCOUNT(
	USER_ID NUMBER NOT NULL CONSTRAINT USER_PK PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(20) NOT NULL,
	PHONE_NO VARCHAR2(20) NOT NULL UNIQUE,
	EMAIL VARCHAR2(30) NOT NULL UNIQUE CHECK(EMAIL LIKE '%@%'),
	PROFILE_PIC BLOB,
	LAST_CREATED_ON  DATE DEFAULT SYSDATE,
	LAST_UPDATED_ON DATE DEFAULT SYSDATE,
	DISTRICT VARCHAR2(50) NOT NULL,
	POSTAL_CODE NUMBER NOT NULL,
	STREET VARCHAR2(50) NOT NULL,
	HOUSE VARCHAR2(50)
);

DROP SEQUENCE SEQ_USER;
CREATE SEQUENCE SEQ_USER
INCREMENT BY  1
START WITH 1
NOCACHE;

CREATE TABLE STAND(
	STAND_ID NUMBER NOT NULL CONSTRAINT STAND_PK PRIMARY KEY,
	STAND_NAME VARCHAR2(50) NOT NULL UNIQUE,
	STAND_IMAGE BLOB
);

DROP SEQUENCE SEQ_STAND;
CREATE SEQUENCE SEQ_STAND
INCREMENT BY 1
START WITH 1
NOCACHE;

CREATE TABLE TRANSACTION(
	TRANSACTION_ID NUMBER NOT NULL CONSTRAINT TRANSACTION_PK PRIMARY KEY,
	TIME DATE DEFAULT SYSDATE,
	AMOUNT NUMBER NOT NULL CHECK(AMOUNT>=0)
);

DROP SEQUENCE SEQ_TRANSACTION;
CREATE SEQUENCE SEQ_TRANSACTION
INCREMENT BY 1
START WITH 1
NOCACHE;

CREATE TABLE ROUTE(
	ROUTE_ID NUMBER NOT NULL CONSTRAINT ROUTE_PK PRIMARY KEY,
	START_STAND_ID NUMBER NOT NULL,
	END_STAND_ID NUMBER NOT NULL,
	CONSTRAINT START_STAND_ROUTE_FK FOREIGN KEY(START_STAND_ID) REFERENCES STAND(STAND_ID) ON DELETE CASCADE,
	CONSTRAINT END_STAND_ROUTE_FK FOREIGN KEY(END_STAND_ID) REFERENCES STAND(STAND_ID) ON DELETE CASCADE,
	CONSTRAINT CHECK_START_END_DIFFERENT CHECK (START_STAND_ID <> END_STAND_ID)
);

DROP SEQUENCE SEQ_ROUTE;
CREATE SEQUENCE SEQ_ROUTE
INCREMENT BY 1
START WITH 1
NOCACHE;

CREATE TABLE ROUTE_STAND(
	ROUTE_STAND_ID NUMBER NOT NULL CONSTRAINT ROUTE_STAND_PK PRIMARY KEY,
	ROUTE_ID NUMBER NOT NULL,
	STAND_ID NUMBER NOT NULL,
	CONSTRAINT ROUTE_STAND_ROUTE_FK FOREIGN KEY(ROUTE_ID) REFERENCES ROUTE(ROUTE_ID),
	CONSTRAINT ROUTE_STAND_STAND_FK FOREIGN KEY(STAND_ID) REFERENCES STAND(STAND_ID)
);

DROP SEQUENCE SEQ_ROUTE_STAND;
CREATE SEQUENCE SEQ_ROUTE_STAND
INCREMENT BY 1
START WITH 1
NOCACHE;

CREATE TABLE SCHEDULE(
	SCHEDULE_ID NUMBER CONSTRAINT SCHEDULE_PK PRIMARY KEY
);

DROP SEQUENCE SEQ_SCHEDULE;
CREATE SEQUENCE SEQ_SCHEDULE
INCREMENT BY 1
START WITH 1
NOCACHE;

CREATE TABLE SCHEDULE_TIME (
	SCHEDULE_ID NUMBER NOT NULL,
	T_TIME INTERVAL DAY(0) TO SECOND(0) NOT NULL,
	CONSTRAINT TIME_SCHEDULE_ID_FK FOREIGN KEY(SCHEDULE_ID) REFERENCES SCHEDULE(SCHEDULE_ID) ON DELETE CASCADE
);

CREATE TABLE BUS_COMPANY(
	BUS_COMPANY_ID NUMBER NOT NULL CONSTRAINT BUS_COMPANY_PK PRIMARY KEY,
	BUS_COMPANY_NAME VARCHAR2(50) NOT NULL,
	BUS_RELATED_MEDIA BLOB
);

DROP SEQUENCE SEQ_BUS_COMPANY;
CREATE SEQUENCE SEQ_BUS_COMPANY
INCREMENT BY 1
START WITH 1
NOCACHE;

CREATE TABLE BUS(
	BUS_ID NUMBER NOT NULL CONSTRAINT BUS_PK PRIMARY KEY,
	BUS_COMPANY_ID NUMBER NOT NULL,
	ROUTE_ID NUMBER NOT NULL,
	SCHEDULE_ID NUMBER NOT NULL,
	BUS_TYPE VARCHAR2(20) NOT NULL,
	SEAT_COUNT NUMBER NOT NULL CHECK(SEAT_COUNT>0),
	BUS_RATING NUMBER NOT NULL CHECK(BUS_RATING BETWEEN 0 AND 5),
	TICKET_PRICE NUMBER NOT NULL CHECK(TICKET_PRICE>0),
	CONSTRAINT BUS_COMPANY_FK FOREIGN KEY(BUS_COMPANY_ID) REFERENCES BUS_COMPANY(BUS_COMPANY_ID) ON DELETE CASCADE,
	CONSTRAINT ROUTE_FK FOREIGN KEY(ROUTE_ID) REFERENCES ROUTE(ROUTE_ID),
	CONSTRAINT SCHEDULE_FK FOREIGN KEY(SCHEDULE_ID) REFERENCES SCHEDULE(SCHEDULE_ID)
);

DROP SEQUENCE SEQ_BUS;
CREATE SEQUENCE SEQ_BUS
INCREMENT BY 1
START WITH 1
NOCACHE;

CREATE TABLE EVENT(
	EVENT_ID NUMBER CONSTRAINT EVENT_PK PRIMARY KEY,
	EVENT_NAME VARCHAR2(50) NOT NULL,
	EVENT_START_TIME DATE NOT NULL,
	EVENT_END_TIME DATE NOT NULL,
	DISCOUNT NUMBER NOT NULL CHECK(DISCOUNT BETWEEN 0 AND 1),
	CONSTRAINT CHECK_START_END_DIFFERENT_EVENT CHECK (EVENT_START_TIME<=EVENT_END_TIME)
);

DROP SEQUENCE SEQ_EVENT;
CREATE SEQUENCE SEQ_EVENT
INCREMENT BY 1
START WITH 1
NOCACHE;

CREATE TABLE REVIEW(
	USER_ID NUMBER NOT NULL,
	BUS_ID NUMBER NOT NULL,
	SCORE NUMBER NOT NULL,
	COMMENTS VARCHAR2(500),
	CONSTRAINT REVIEW_PK PRIMARY KEY(USER_ID,BUS_ID),
	CONSTRAINT USER_FK FOREIGN KEY(USER_ID) REFERENCES USER_ACCOUNT(USER_ID) ON DELETE SET NULL,
	CONSTRAINT BUS_FK FOREIGN KEY(BUS_ID) REFERENCES BUS(BUS_ID) ON DELETE CASCADE
);

CREATE TABLE DISTANCE(
	DISTANCE_ID NUMBER NOT NULL CONSTRAINT DISTANCE_PK PRIMARY KEY,
	STARTING_STAND NUMBER NOT NULL,
	ENDING_STAND NUMBER NOT NULL,
	TRAVEL_DISTANCE NUMBER NOT NULL,
	CONSTRAINT START_FK FOREIGN KEY(STARTING_STAND) REFERENCES STAND(STAND_ID) ON DELETE CASCADE,
	CONSTRAINT END_FK FOREIGN KEY(ENDING_STAND) REFERENCES STAND(STAND_ID) ON DELETE CASCADE,
	CONSTRAINT CHECK_START_END_DIFFERENT_DISTANCE CHECK (STARTING_STAND <> ENDING_STAND)
);

DROP SEQUENCE SEQ_DISTANCE;
CREATE SEQUENCE SEQ_DISTANCE
INCREMENT BY 1
START WITH 1
NOCACHE;

CREATE TABLE TICKET(
	TICKET_ID NUMBER CONSTRAINT TICKET_PK PRIMARY KEY,
	USER_ID NUMBER NOT NULL,
	BUS_ID NUMBER NOT NULL,
	TRANSACTION_ID NUMBER NOT NULL,
	STARTING_STAND NUMBER NOT NULL,
	ENDING_STAND NUMBER NOT NULL,
	DISTANCE_ID NUMBER NOT NULL,
	EVENT_ID NUMBER,
	TRAVEL_TIME DATE NOT NULL,
	SEAT_NUMBER NUMBER NOT NULL,
	TICKET_PRICE NUMBER NOT NULL CHECK(TICKET_PRICE>0),
	CONSTRAINT USER_FK_T FOREIGN KEY(USER_ID) REFERENCES USER_ACCOUNT(USER_ID) ON DELETE SET NULL ,
	CONSTRAINT BUS_FK_T FOREIGN KEY(BUS_ID) REFERENCES BUS(BUS_ID) ON DELETE SET NULL ,
	CONSTRAINT TRANSACTION_FK_T FOREIGN KEY(TRANSACTION_ID) REFERENCES TRANSACTION(TRANSACTION_ID),
	CONSTRAINT START_FK_T FOREIGN KEY(STARTING_STAND) REFERENCES STAND(STAND_ID) ON DELETE SET NULL ,
	CONSTRAINT END_FK_T FOREIGN KEY(ENDING_STAND) REFERENCES STAND(STAND_ID) ON DELETE SET NULL,
	CONSTRAINT DISTANCE_FK_T FOREIGN KEY(DISTANCE_ID) REFERENCES DISTANCE(DISTANCE_ID)
);

DROP SEQUENCE SEQ_TICKET;
CREATE SEQUENCE SEQ_TICKET
INCREMENT BY 1
START WITH 1
NOCACHE;

DROP TABLE LOG;
CREATE TABLE LOG(
	LOG_ID NUMBER CONSTRAINT LOG_PK PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	TIME DATE NOT NULL,
	PARAMETERS VARCHAR2(500) NOT NULL
);

DROP SEQUENCE SEQ_LOG;
CREATE SEQUENCE SEQ_LOG
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE TABLE WEBSITE_REVIEW(
	USER_ID NUMBER NOT NULL,
	SCORE NUMBER NOT NULL,
	COMMENTS VARCHAR2(500),
	CREATED_ON DATE DEFAULT SYSDATE,
	LAST_UPDATED_ON DATE DEFAULT SYSDATE,
	CONSTRAINT WEBSITE_REVIEW_PK PRIMARY KEY(USER_ID),
	CONSTRAINT WEBSITE_USER_FK FOREIGN KEY(USER_ID) REFERENCES USER_ACCOUNT(USER_ID) ON DELETE SET NULL
);